# Generated by Django 2.1.7 on 2019-02-25 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='owner',
            field=models.ForeignKey(default=1, on_delete='on_delete', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
